# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 21:25
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Post = apps.get_model('post', 'Post')
    User = apps.get_model('auth', 'User')
    user_count = len(User.objects.all())
    for i in range(20):
        user = User.objects.get(pk=(i%user_count)+1)
        post = Post.objects.create(author=user, text='text{}'.format(i))
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

