# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 21:25
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    from django.contrib.auth.models import User
    user = User.objects.create_user(username='batman',
                                    email='thedarkknight@gotham.com',
                                    password='batmanpassword')
    user.save()
    user = User.objects.create_user(username='spiderman',
                                    email='spidey@web.com',
                                    password='spidermanpassword')
    user.save()
    user = User.objects.create_user(username='goku',
                                    email='goku@dbz.com',
                                    password='gokupassword')
    user.save()
    user = User.objects.create_superuser(username='trunks',
                                         email='purplehair@dbz.com',
                                         password='trunkspassword')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('authtoken', '0002_auto_20160226_1747')
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

    run_before = [
        ('post', '0002_auto_20180310_2125')
    ]
